### ISSUE TITLE
MyDashWallet.Services.Full.csproj not found

### ISSUE THREAD

**Issue by pavik** [DeltaEngine/MyDashWallet#1]
Two projects' files are not found: `MyDashWallet.Services.Full.csproj` and `MyDashWallet.Services.Full.PrivateSendService.csproj`. Folder `Services\Full` does not exist at all.

**Comment by BenjaminNitschke** [comment]
You can remove those references, everything runs with the Testnet, the private mixing service is not needed for local use. In the next release we will release example-versions of those services if anyone else is interested.
