### ISSUE TITLE
explorer.mydashwallet.org needs update to v18.0.1. Certificate also expired.

### ISSUE THREAD

**Issue by greatwolf** [DeltaEngine/MyDashWallet#12]
Just wanted to bring up 'explorer.mydashwallet.org' needs to upgrade to v18.0.1 and the certificate is also expired and needs a renew.

I've also pinged and notified `/u/MyDashWallet` on reddit and on twitter @mydashwallet regarding the issue.

**Comment by BenjaminNitschke** [comment]
Yep, we are aware and will fix it soon, thanks for the heads up.

Regards,
MyDashWallet Support

**Comment by greatwolf** [comment]
Currently getting 502 bad gateway.

**Comment by greatwolf** [comment]
Any updates on this? The site's been timing out for me for couple weeks.

**Comment by BenjaminNitschke** [comment]
Sorry for the long delay, we don't really use the explorer much except for a fallback on https://mydashwallet.org
The server was restarting over and over with a block issue that required a reindex (probably after the upgrade to 18.1 2 months ago), now it is all reindexed and working again .. we also added it to our monitoring tools to quickly resolve issues in the future.
