### ISSUE TITLE
Don't pull scripts from greasyfork.org

### ISSUE THREAD

**Issue by JasonBarnabe** [DeltaEngine/MyDashWallet#2]
[The one you reference](https://github.com/DeltaEngine/MyDashWallet/blob/master/Views/Home/Index.cshtml#L13) was infected with malware and has been deleted.

greasyfork.org is not a CDN in any case.

**Comment by BenjaminNitschke** [comment]
Thanks for reporting this, the bad script/library was removed, we haven't used it for over a year, but didn't properly clean up, it was more for experimenting around with CryptoLib, now that HD wallets, hardware wallets, etc. are used the script is not longer needed anyway.

**Comment by BenjaminNitschke** [comment]
https://github.com/DeltaEngine/MyDashWallet/commit/54b73658120eb601929011e644792bd6a1291d84
