### ISSUE TITLE
old mixing didn't work

### ISSUE THREAD

**Issue by sweetpotatoz** [DeltaEngine/MyDashWallet#4]
https://old.mydashwallet.org/Mixing
sent dash to mix, but never returned anything to my "Address to send to anonymously"
<deleted>
ouch now i open this issue, no longer anonymous :(

**Comment by BenjaminNitschke** [comment]
Hi,

please use support@mydashwallet.org to contact the support team and get
help, the initial transaction or address is all we need to check, both this
and the target address are deleted once the mixing is done.

Looks like your mixing request is still being processed, there have been a
lot of smaller mixings. It can take up to 12 hours if there is not enough
premixed Dash available at the time you start.

There is currently almost enough Dash premixed, but if that doesn't work,
the system will automatically credit even partially mixed Dash (remember
that we do not do the mixing, it is done by the Dash Masternode network and
out of our control how fast it goes, usually for small amounts it is mixed
in a few minutes).

Regards,
Benjamin

**Comment by sweetpotatoz** [comment]
received.  thanks
