### ISSUE TITLE
Balance at 0, cannot acces to my funds

### ISSUE THREAD

**Issue by lugaxker** [DeltaEngine/MyDashWallet#5]
Hello, 

I sent funds to my wallet but my balance is 0 and I cannot sent the funds to another address. 

However the funds are here because I see below the Qr code: 

"Your older addresses
X**************************************      *.******** DASH"

I don't have any seed. How can I access my private key?

**Comment by lugaxker** [comment]
I managed to download the `.HDSeed` encrypted file, but I don't know how to decrypt it.

**Comment by BenjaminNitschke** [comment]
Hi. You should send support requests to support@mydashwallet.org to reach
the support personal.

The free coinmarketcap api stopped working last week and we had to switch
to exchange prices and fix some things on the backend. The site should now
work normally again.

Your seed is not known by the browser, you should have written it down when
the wallet was created. Private keys can be displayed if the wallet is in
the private key format, more info in the help section of the site.

Regards,
MyDashWallet

**Comment by lugaxker** [comment]
Hello, 

Thank you for the quick update!

I managed to spend the funds from the "Old Website" tab. It didn't work yesterday, but it worked today. 

Next time I will use a 12-word seed.

Regards, 
Ludovic Lars.
