### ISSUE TITLE
https://explorer.mydashwallet.org is currently borked.

### ISSUE THREAD

**Issue by greatwolf** [DeltaEngine/MyDashWallet#7]
Title's self-explanatory. Going to the site frontend explorer.mydashwallet.org will just show an error icon on the top bar. It may be out of sync or missing connection with other nodes on the network. None of the transactions and blocks are showing properly at the time of this posting.

Also https://explorer.mydashwallet.org/status shows `API ERROR: Dash JSON-RPC: Request Error: connect ECONNREFUSED 127.0.0.1:9998`.

**Comment by BenjaminNitschke** [comment]
Thanks for the notification, the node for the explorer ran out of space.
Fixed it now

**Comment by greatwolf** [comment]
Thanks, seems to be fine now.
